version: '3'
services:
  meeting:
    image: meeting  #镜像
    container_name: meeting-app  #容器名称  
    build:
      context: .
      dockerfile: ./build/meeting-app.Dockerfile 
    ports:
      - 127.0.0.1:3000:3000
  meeting-chat:
    image: meeting-chat  #镜像
    container_name: meeting-chat  #容器名称  
    build:
      context: .
      dockerfile: ./build/meeting-chat.Dockerfile
  nest-service:
    image: nest-service  #镜像
    container_name: nest-service  #容器名称  
    build:
      context: .
      dockerfile: ./build/nest-service.Dockerfile 